language: python
python:
  - "2.6"
install: pip install Jinja2 --use-mirrors
before_script: cd slides
script: make --jobs 2 --keep-going
branches:
  only:
    - gh-pages
notifications:
  email:
    recipients:
      - daniel+travis-ci@trvx.org
    on_success: change
    on_failure: always
